// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxI87R_9NrwMIRLJwCn2M2MY9968piKak',
    appId: '1:973764054928:web:3c2460360b0e1e6d06ad15',
    messagingSenderId: '973764054928',
    projectId: 'practise-app-6a1fd',
    authDomain: 'practise-app-6a1fd.firebaseapp.com',
    storageBucket: 'practise-app-6a1fd.appspot.com',
    measurementId: 'G-QZV9B5HY51',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFhyXEoI_SCo9o83zho30UR2YzZqVf55w',
    appId: '1:973764054928:ios:5eaa59ef4d4661fa06ad15',
    messagingSenderId: '973764054928',
    projectId: 'practise-app-6a1fd',
    storageBucket: 'practise-app-6a1fd.appspot.com',
    iosBundleId: 'com.example.practiseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxI87R_9NrwMIRLJwCn2M2MY9968piKak',
    appId: '1:973764054928:web:677674c05125c75f06ad15',
    messagingSenderId: '973764054928',
    projectId: 'practise-app-6a1fd',
    authDomain: 'practise-app-6a1fd.firebaseapp.com',
    storageBucket: 'practise-app-6a1fd.appspot.com',
    measurementId: 'G-PNNMYEKS0C',
  );
}
